### ISSUE TITLE
Small typo in doc

### ISSUE THREAD

**Issue by AndersGerner** [ssbeefeater/axios-request#1]
Thought it was a bit much to make a PR for 1 char.

In your documentation is says:

requestInstance.isPending(method = '') // returns true when a request is on the fly
requestInstance.isUpdating(method = 'post') // returns true when a request is on the fly after interval request
equestInstance.isPolling(method = 'get') // returns true when polling is enabled

There is missing an "R" in the last request example.

requestInstance.isPending(method = '') // returns true when a request is on the fly
requestInstance.isUpdating(method = 'post') // returns true when a request is on the fly after interval request
**r**equestInstance.isPolling(method = 'get') // returns true when polling is enabled

:)

**Comment by ssbeefeater** [comment]
thank you!
